version: '3.8'

services:
  train-ticket-assistant:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # 从 .env.production 文件加载环境变量
      - DIFY_API_KEY=${DIFY_API_KEY}
      - DIFY_BASE_URL=${DIFY_BASE_URL:-https://api.dify.ai/v1}
      - DIFY_APP_ID=${DIFY_APP_ID}
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL 证书目录
    depends_on:
      - train-ticket-assistant
    restart: unless-stopped
